"""contratos_regimen_fk_fecha_fin_nullable

Revision ID: 155b20c28fc7
Revises: 2e5e38bf40ca
Create Date: 2026-06-17 16:09:36.404569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '155b20c28fc7'
down_revision = '2e5e38bf40ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr_contratos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regimen_laboral_id', sa.Integer(), nullable=True))
        batch_op.alter_column('fecha_fin',
               existing_type=sa.DATE(),
               nullable=True)

    # Migrar valores antiguos de 'tipo' a regimen_laboral_id
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE hr_contratos c
        JOIN hr_regimenes_laborales r ON LOWER(r.nombre) = LOWER(c.tipo)
        SET c.regimen_laboral_id = r.id
        WHERE c.tipo IS NOT NULL
    """))

    # Para contratos cuyo tipo no tenga match, asignar el primer régimen activo disponible
    connection.execute(sa.text("""
        UPDATE hr_contratos c
        SET c.regimen_laboral_id = (
            SELECT id FROM hr_regimenes_laborales WHERE activo = 1 ORDER BY orden, id LIMIT 1
        )
        WHERE c.regimen_laboral_id IS NULL
    """))

    with op.batch_alter_table('hr_contratos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'hr_regimenes_laborales', ['regimen_laboral_id'], ['id'])
        batch_op.alter_column('regimen_laboral_id',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr_contratos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', mysql.VARCHAR(length=30), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('fecha_fin',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('regimen_laboral_id')

    # ### end Alembic commands ###
