"""initial clean migration

Revision ID: 2e5e38bf40ca
Revises: 
Create Date: 2026-06-16 12:17:08.187262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5e38bf40ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('hr_cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_dependencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('hr_estados_civiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('hr_estados_funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('hr_estados_zafral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('hr_generos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('hr_niveles_educativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('hr_regimenes_laborales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('hr_tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_tipos_zafral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('hr_uruguay_impulsa_funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_funcion', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('apellido', sa.String(length=150), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('estado_civil', sa.String(length=30), nullable=True),
    sa.Column('tiene_hijos', sa.Boolean(), nullable=False),
    sa.Column('cantidad_hijos', sa.Integer(), nullable=False),
    sa.Column('cedula_identidad', sa.String(length=30), nullable=False),
    sa.Column('calle', sa.String(length=200), nullable=True),
    sa.Column('entre_las_calles', sa.String(length=200), nullable=True),
    sa.Column('zona', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('mail', sa.String(length=150), nullable=True),
    sa.Column('primaria_estado', sa.String(length=20), nullable=True),
    sa.Column('ciclo_basico_estado', sa.String(length=20), nullable=True),
    sa.Column('bachillerato_estado', sa.String(length=20), nullable=True),
    sa.Column('terciario_estado', sa.String(length=20), nullable=True),
    sa.Column('capacitaciones', sa.Text(), nullable=True),
    sa.Column('trabajos_anteriores', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula_identidad')
    )
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ci', sa.String(length=30), nullable=False),
    sa.Column('nombres', sa.String(length=150), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('genero', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('pais_nacimiento', sa.String(length=100), nullable=True),
    sa.Column('departamento_nacimiento', sa.String(length=100), nullable=True),
    sa.Column('estado_civil', sa.String(length=30), nullable=True),
    sa.Column('dependencia_id', sa.Integer(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('regimen_laboral', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('motivo_baja', sa.String(length=255), nullable=True),
    sa.Column('inasistencias', sa.Integer(), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('otro_contacto', sa.String(length=150), nullable=True),
    sa.Column('calle', sa.String(length=200), nullable=True),
    sa.Column('entre_calles', sa.String(length=200), nullable=True),
    sa.Column('zona', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('nivel_educativo', sa.String(length=100), nullable=True),
    sa.Column('otras_capacitaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['hr_cargos.id'], ),
    sa.ForeignKeyConstraint(['dependencia_id'], ['hr_dependencias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ci')
    )
    op.create_table('hr_funcionarios_zafrales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ci', sa.String(length=30), nullable=False),
    sa.Column('nombres', sa.String(length=150), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('genero', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('pais_nacimiento', sa.String(length=100), nullable=True),
    sa.Column('departamento_nacimiento', sa.String(length=100), nullable=True),
    sa.Column('estado_civil', sa.String(length=30), nullable=True),
    sa.Column('dependencia_id', sa.Integer(), nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('tipo_zafral', sa.String(length=50), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('regimen_laboral', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('motivo_baja', sa.String(length=255), nullable=True),
    sa.Column('inasistencias', sa.Integer(), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('otro_contacto', sa.String(length=150), nullable=True),
    sa.Column('calle', sa.String(length=200), nullable=True),
    sa.Column('entre_calles', sa.String(length=200), nullable=True),
    sa.Column('zona', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('nivel_educativo', sa.String(length=100), nullable=True),
    sa.Column('otras_capacitaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dependencia_id'], ['hr_dependencias.id'], ),
    sa.ForeignKeyConstraint(['tarea_id'], ['hr_tareas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ci')
    )
    op.create_table('two_factor_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['hr_funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('sueldo_nominal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('documento_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['hr_funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_trabajos_anteriores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=200), nullable=False),
    sa.Column('periodo', sa.String(length=100), nullable=True),
    sa.Column('seccion', sa.String(length=150), nullable=True),
    sa.Column('cargo', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['hr_funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hr_trabajos_anteriores')
    op.drop_table('hr_contratos')
    op.drop_table('hr_asistencias')
    op.drop_table('two_factor_codes')
    op.drop_table('hr_funcionarios_zafrales')
    op.drop_table('hr_funcionarios')
    op.drop_table('activity_logs')
    op.drop_table('hr_uruguay_impulsa_funcionarios')
    op.drop_table('hr_tipos_zafral')
    op.drop_table('hr_tareas')
    op.drop_table('hr_regimenes_laborales')
    op.drop_table('hr_niveles_educativos')
    op.drop_table('hr_generos')
    op.drop_table('hr_estados_zafral')
    op.drop_table('hr_estados_funcionario')
    op.drop_table('hr_estados_civiles')
    op.drop_table('hr_dependencias')
    op.drop_table('hr_cargos')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
