"""contrato_funcionario_zafral_fk

Revision ID: bf4c829d7f0f
Revises: 155b20c28fc7
Create Date: 2026-06-17 16:34:53.595430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf4c829d7f0f'
down_revision = '155b20c28fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr_contratos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funcionario_zafral_id', sa.Integer(), nullable=True))
        batch_op.alter_column('funcionario_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.create_foreign_key(None, 'hr_funcionarios_zafrales', ['funcionario_zafral_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr_contratos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('funcionario_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('funcionario_zafral_id')

    # ### end Alembic commands ###
